config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations], controllers: {
    sessions: "admins/sessions"
  }
  devise_for :customers, controllers: {
    sessions: "customers/sessions",
    registrations: "customers/registrations"
  }
  root 'static_pages#home'
  get 'about', to: "static_pages#about"

  namespace :admin do
    resources :products
  end

  scope module: :customer do
    resources :products, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @products = Product.with_attached_image.order(created_at: :DESC).limit(3)
  end

  def about; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class=container>
  <h2 class="text-center mb-4">Admin</h2>
  <div class="row mb-4">
    <h4>管理者ページ</h4>
    <div>
      商品の管理者ページは右からアクセスできます
      <%= link_to admin_products_path, admin_products_path%> <br>
      管理者ページのためログインが必要です。以下をお使いください。管理者アカウントの新規登録はできません。
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-6">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">Email:</th>
            <th scope="col">admin1@example.com</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">Password:</th>
            <td>password</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="container">
<h2>New Items</h2>
<div class="row">
  <div class="col-6">
    <div id="carouselExampleCaptions" class="carousel carousel-dark slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">

        <% @products.each_with_index do |product, i|%>
          <% if i==0%>
            <div class="carousel-item active" data-bs-interval="4000">
          <% else %>
            <div class="carousel-item" data-bs-interval="4000">
          <% end %>
            <%= link_to (image_tag product.image,  class: "d-block user_image"), product_path(product), class:"ratio ratio-1x1"%>
          <div class="carousel-caption d-none d-md-block">
            <h5><%=product.name%></h5>
            <p><%=product.manufacturer%></p>
          </div>
        </div>
        <% end %>

      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
  <%=image_tag "bunbouguset.png", class: "col-6 user_image align-self-start"%>
</div>
</div>