config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations], controllers: {
    sessions: "admins/sessions"
  }
  devise_for :customers, controllers: {
    sessions: "customers/sessions",
    registrations: "customers/registrations"
  }
  root 'static_pages#home'
  get 'about', to: "static_pages#about"

  namespace :admin do
    resources :products
  end

  scope module: :customer do
    resources :products, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/product.rb
class Product < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :manufacturer
    validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
    validates :description
    validates :stock, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
    validates :image
  end
  has_one_attached :image
  has_many :cart_items, dependent: :destroy

  def self.get_all_and_sort(sort_param)
    products = self.with_attached_image
    case sort_param
    when "price_low_to_high"
      products.order(:price)
    when "price_high_to_low"
      products.order(price: :DESC)
    when "date_old_to_new"
      products.order(:created_at)
    else
      products.order(created_at: :DESC)
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @pagy, @products = pagy(Product.with_attached_image.order(created_at: :DESC), items: 10)
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path, notice: "Product was created!"
    else
      render "new", status: :unprocessable_entity
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path, notice: "Product was updated!"
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    if Product.find(params[:id]).destroy
      redirect_to admin_products_path, notice: "Product was deleted!"
    else
      render "index", status: :unprocessable_entity
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :manufacturer, :price,
                                    :description, :stock, :image)
  end
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController
  def index
    sort_products = Product.get_all_and_sort(sort_param)
    @pagy, @products = pagy(sort_products, items: 12)
  end

  def show
    @product = Product.find(params[:id])
  end

  private

  def sort_param
    params[:sort]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @pagy, @products = pagy(Product.all)
  end

  def create
    @product = Product.new(product_params)
    @product.save
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
    else
    end
  end

  def destroy
    Product.find(params[:id]).destroy
  end

  private

    def product_params
      params.require(:product).permit(:name, :manufacturer, :price,
                                  :description, :stock, :image)
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
  def index
    
  end

  def show
    
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<div class="container">
<h2 class="text-center mb-4">Edit product</h2>
<div class="d-flex flex-column align-items-center">
<%= link_to "Back", admin_products_path, class: "btn btn-primary align-self-baseline offset-md-2"%>
  <div class="col-lg-6">
  <%= form_with model: @product, url: admin_product_path(@product) do |f|%>

    <div class="mb-3">
      <%= f.label :name, class:"form-label" %>
      <%= f.text_field :name, class:"form-control"%>
    </div>

    <div class="mb-3">
      <%= f.label :manufacturer, class: "form-label" %>
      <%= f.text_field :manufacturer, class: "form-control"%>
    </div>

    <div class="mb-3">
      <%= f.label :price, class: "form-label" %>
      <%= f.number_field :price, class: "form-control"%>
    </div>

    <div class="mb-3">
      <%= f.label :stock, class: "form-label" %>
      <%= f.number_field :stock, class: "form-control"%>
    </div>

    <div class="mb-3">
      <%= f.label :description, class: "form-label" %>
      <%= f.text_area :description, rows: 4,class: "form-control"%>
    </div>

    <div class="mb-5">
      <%= f.label :image, class: "form-label" %>
      <%= f.file_field :image,class: "form-control"%>
    </div>

  <div class="mb-4 d-grid">
    <%= f.submit "Edit product", class: "btn btn-primary"  %>
  </div>

  <% end %>

  <div class="mb-4 d-grid">
    <%= link_to "Delete", admin_product_path(@product),
                                       data: { "turbo-method": :delete }, class: "btn btn-danger"%>
  </div>
  </div>
</div>
</div>

app/views/admin/products/index.html.erb
<div class="container">
<h2 class="text-center">Products</h2>
<%= link_to "Add new product", new_admin_product_path, class: "btn btn-primary"%>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Image</th>
      <th scope="col">Name</th>
      <th scope="col">Manufacturer</th>
      <th scope="col">Price</th>
      <th scope="col">Stock</th>
      <th scope="col">Created_at</th>
      <th scope="col">Updated_at</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <th scope="row">
        <%= link_to image_tag( product.image, class: "user_image") , product_path(product), class: "ratio ratio-1x1"%>
          <%# image_tag product.image, class: "img-fluid", size: '' %>
        </th>
        <td><%= product.name %></td>
        <td><%= product.manufacturer %></td>
        <td><%= product.price %></td>
        <td><%= product.stock %></td>
        <td><%= l product.created_at %></td>
        <td><%= l product.updated_at %></td>
        <td><%= link_to "Edit", edit_admin_product_path(product) %></td>
      </tr>
    <% end%>
  </tbody>
</table>

  <div class="d-flex justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container">
<h2 class="text-center mb-4">Create new product</h2>
<div class="d-flex flex-column align-items-center">
<%= link_to "Back", admin_products_path, class: "btn btn-primary align-self-baseline offset-md-2"%>
  <%= form_with model: @product, url: admin_products_path, class: "col-lg-6" do |f|%>

    <div class="mb-3">
      <%= f.label :name, class:"form-label" %>
      <%= f.text_field :name, class:"form-control"%>
    </div>

    <div class="mb-3">
      <%= f.label :manufacturer, class: "form-label" %>
      <%= f.text_field :manufacturer, class: "form-control"%>
    </div>

    <div class="mb-3">
      <%= f.label :price, class: "form-label" %>
      <%= f.number_field :price, class: "form-control"%>
    </div>

    <div class="mb-3">
      <%= f.label :stock, class: "form-label" %>
      <%= f.number_field :stock, class: "form-control"%>
    </div>

    <div class="mb-3">
      <%= f.label :description, class: "form-label" %>
      <%= f.text_area :description, rows: 4,class: "form-control"%>
    </div>

    <div class="mb-5">
      <%= f.label :image, class: "form-label" %>
      <%= f.file_field :image,class: "form-control"%>
    </div>

  <div class="mb-4 d-grid">
    <%= f.submit "Create product", class: "btn btn-primary"  %>
  </div>

  <% end %>
</div>
</div>