config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations], controllers: {
    sessions: "admins/sessions"
  }
  devise_for :customers, controllers: {
    sessions: "customers/sessions",
    registrations: "customers/registrations"
  }
  root 'static_pages#home'
  get 'about', to: "static_pages#about"

  namespace :admin do
    resources :products
  end

  scope module: :customer do
    resources :products, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable :registerable,:recoverable,
  devise :database_authenticatable,
         :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  with_options presence: true do
    validates :customer_id
    validates :product_id
    validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  end
  attribute :quantity, :integer, default: 1
  belongs_to :product
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :recoverable,
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :manufacturer
    validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
    validates :description
    validates :stock, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
    validates :image
  end
  has_one_attached :image
  has_many :cart_items, dependent: :destroy

  def self.get_all_and_sort(sort_param)
    products = self.with_attached_image
    case sort_param
    when "price_low_to_high"
      products.order(:price)
    when "price_high_to_low"
      products.order(price: :DESC)
    when "date_old_to_new"
      products.order(:created_at)
    else
      products.order(created_at: :DESC)
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @pagy, @products = pagy(Product.with_attached_image.order(created_at: :DESC), items: 10)
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path, notice: "Product was created!"
    else
      render "new", status: :unprocessable_entity
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path, notice: "Product was updated!"
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    if Product.find(params[:id]).destroy
      redirect_to admin_products_path, notice: "Product was deleted!"
    else
      render "index", status: :unprocessable_entity
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :manufacturer, :price,
                                    :description, :stock, :image)
  end
end

app/controllers/admins/passwords_controller.rb
# frozen_string_literal: true

class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController
  def index
    sort_products = Product.get_all_and_sort(sort_param)
    @pagy, @products = pagy(sort_products, items: 12)
  end

  def show
    @product = Product.find(params[:id])
  end

  private

  def sort_param
    params[:sort]
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @pagy, @products = pagy(Product.all)
  end

  def create
    @product = Product.new(product_params)
    @product.save
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
    else
    end
  end

  def destroy
    Product.find(params[:id]).destroy
  end

  private

    def product_params
      params.require(:product).permit(:name, :manufacturer, :price,
                                  :description, :stock, :image)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @products = Product.with_attached_image.order(created_at: :DESC).limit(3)
  end

  def about; end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
  def index
    
  end

  def show
    
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li><a href="<%=root_path%>" class="nav-link px-2 text-muted">Home</a></li>
      <li><a href="<%=products_path%>" class="nav-link px-2 text-muted">Products</a></li>
      <li><a href="<%=about_path%>" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">&copy; 2023 Company, Inc</p>
  </footer>
</div>

app/views/layouts/_header.html.erb
  <header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <%=image_tag "FeFe-logos.png", width: 100 %>
        </a>

        <ul class="nav ms-2 col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="<%=root_path%>" class="nav-link px-2 text-white">Home</a></li>
          <li><a href="<%=products_path%>" class="nav-link px-2 text-white">Products</a></li>
          <li><a href="<%=about_path%>" class="nav-link px-2 text-white">Admin</a></li>
        </ul>

        <%# <form class="col-10 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
        </form> %>

        <% if customer_signed_in? %>
          <div class="text-end">
            <a type="button" href="<%=edit_customer_registration_path%>" class="btn btn-outline-light me-2">Account</a>
            <%= link_to "Log out", destroy_customer_session_path,
                                       data: { "turbo-method": :delete }, class: "btn btn-outline-light me-2"%>
            <%= link_to "Cart", cart_items_path, class: "btn btn-outline-light me-2"%>
          </div>
        <% else %>
          <div class="text-end">
            <a type="button" href="<%=new_customer_session_path%>" class="btn btn-outline-light me-2">Login</a>
            <a href="<%=new_customer_registration_path%>" type="button" class="btn btn-warning">Sign up</a>
          </div>
        <% end %>
      </div>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
      <main class="mt-4 mb-5">
        <div class="d-flex flex-column align-items-center">
        <% if flash[:notice] %>
        <div class="alert alert-success text-center col-5" role="alert">
          <%= notice %>
        </div>
        <% end %>
        <% if flash[:alert] %>
        <div class="alert alert-danger text-center col-5" role="alert">
          <%= alert %>
        </div>
        <% end %>
        </div>

        <%= yield %>
      </main>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>