config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations], controllers: {
    sessions: "admins/sessions"
  }
  devise_for :customers, controllers: {
    sessions: "customers/sessions",
    registrations: "customers/registrations"
  }
  root 'static_pages#home'
  get 'about', to: "static_pages#about"

  namespace :admin do
    resources :products
  end

  scope module: :customer do
    resources :products, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  with_options presence: true do
    validates :customer_id
    validates :product_id
    validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  end
  attribute :quantity, :integer, default: 1
  belongs_to :product
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :recoverable,
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @cart_items = current_customer.cart_items.eager_load(product: { image_attachment: :blob })
    @total = @cart_items.sum("quantity * price")
    @total_quantity = @cart_items.sum(:quantity)
  end

  def update
    @cart_item = current_customer.cart_items.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path, notice: "Quantity was changed"
  end

  def destroy
    if current_customer.cart_items.find(params[:id]).destroy
      redirect_to cart_items_path, status: :see_other, notice: "A cart item was deleted"
    else
      render "index", status: :unprocessable_entity
    end
  end

  def create
    @cart_item = current_customer.cart_items.find_by(product_id: params[:cart_item][:product_id])
    if @cart_item
      @cart_item.increment(:quantity, params[:cart_item][:quantity].to_i)
      redirect_to cart_items_path, notice: "Quantity was changed"
    elsif current_customer.cart_items.create(cart_item_params)
      redirect_to cart_items_path, notice: "Add a item to cart"
    else
      render "index", status: :unprocessable_entity, alert: "Failed to add a item to card"
    end
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity, :product_id)
  end
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController
  def index
    sort_products = Product.get_all_and_sort(sort_param)
    @pagy, @products = pagy(sort_products, items: 12)
  end

  def show
    @product = Product.find(params[:id])
  end

  private

  def sort_param
    params[:sort]
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
  def index
    
  end

  def show
    
  end
end

app/views/customer/cart_items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md">
      <h2 class="border-bottom border-2 p-2">Shopping cart</h2>
      <% if @total_quantity == 0 %>
      <h4>No item<h4>
      <% else %>
      <% @cart_items.each do |cart_item| %>
        <div class="d-flex border-bottom border-2 p-4">
          <div class="col-md-2 col-2 me-3">
            <%= link_to image_tag(cart_item.product.image, class: "user_image"), product_path(cart_item.product), class: "ratio ratio-1x1" %>
          </div>
          <div class="col">
            <div class="d-flex">
            
              <div class="col">
                <h5><%= cart_item.product.name %></h5>
                <div class="mb-2"><%= cart_item.product.manufacturer %></div>
                <h4>¥<%= cart_item.product.price %></h4>
              </div>

              <div class="d-flex">
                <div class="mt-2 me-1">Qty.</div>
                <%= button_to cart_item_path(cart_item, cart_item: { product_id: cart_item.product_id, quantity: cart_item.quantity-1 }), data: { "turbo-method": :patch }, method: :patch,class: "btn", id: "minusitem" do%>
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-dash-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z"/>
                </svg>
                <% end %>
                <div class="mt-2"><%=cart_item.quantity%></div>
                <%= button_to cart_item_path(cart_item, cart_item: { product_id: cart_item.product_id, quantity: cart_item.quantity+1 }), data: { "turbo-method": :patch }, method: :patch,class: "btn", id: "plusitem" do%>
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                  </svg>
                <% end %>
              </div>
            </div>
          </div>
            <div class="col-2 ms-auto align-self-end">
              <%= button_to cart_item_path(cart_item), data: { "turbo-method": :delete}, method: :delete, class: "btn", id: "deleteitem" do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M6.5 1a.5.5 0 0 0-.5.5v1h4v-1a.5.5 0 0 0-.5-.5h-3ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1H3.042l.846 10.58a1 1 0 0 0 .997.92h6.23a1 1 0 0 0 .997-.92l.846-10.58Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                </svg>
              <% end %>
            </div>
        </div>
      <% end %>
      <% end %>
    </div>


    <div class=" col-lg-4 p-3">
      <div class="">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-primary">Total</span>
          <span class="badge bg-primary rounded-pill"><%=@total_quantity%></span>
        </h4>
        <ul class="list-group mb-3">
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">Subtotal</h6>
              <small class="text-muted"></small>
            </div>
            <span class="text-muted">¥<%=@total%></span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">Shipping fee</h6>
              <small class="text-muted">Calculated at check out</small>
            </div>
            <span class="text-muted"></span>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <span>Total</span>
            <strong>¥<%=@total%></strong>
          </li>
        </ul>
      </div>
    </div>


  </div>
</div>